# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 18:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Капитан команды ещё не дал описание.', max_length=2000)),
                ('min_rank', models.CharField(choices=[('UN', 'Без ранга'), ('S1', 'Сильвер 1'), ('S2', 'Сильвер 2'), ('S3', 'Сильвер 3'), ('S4', 'Сильвер 4'), ('S5', 'Сильвер Элита'), ('S6', 'Сильвер Великий Магистр'), ('N1', 'Золотая Звезда 1'), ('N2', 'Золотая Звезда 2'), ('N3', 'Золотая Звезда 3'), ('N4', 'Золотая Звезда Магистр'), ('M1', 'Магистр Хранитель 1'), ('M2', 'Магистр Хранитель 2'), ('M3', 'Магистр Хранитель Элита'), ('M4', 'Заслуженный Магистр Хранитель'), ('L1', 'Легендарный Беркут'), ('L2', 'Легендарный Беркут Магистр'), ('SM', 'Великий Магистр Высшего Ранга'), ('GE', 'Всемирная Элита')], default='UN', max_length=2)),
                ('max_rank', models.CharField(choices=[('UN', 'Без ранга'), ('S1', 'Сильвер 1'), ('S2', 'Сильвер 2'), ('S3', 'Сильвер 3'), ('S4', 'Сильвер 4'), ('S5', 'Сильвер Элита'), ('S6', 'Сильвер Великий Магистр'), ('N1', 'Золотая Звезда 1'), ('N2', 'Золотая Звезда 2'), ('N3', 'Золотая Звезда 3'), ('N4', 'Золотая Звезда Магистр'), ('M1', 'Магистр Хранитель 1'), ('M2', 'Магистр Хранитель 2'), ('M3', 'Магистр Хранитель Элита'), ('M4', 'Заслуженный Магистр Хранитель'), ('L1', 'Легендарный Беркут'), ('L2', 'Легендарный Беркут Магистр'), ('SM', 'Великий Магистр Высшего Ранга'), ('GE', 'Всемирная Элита')], default='GE', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
